name: Maven Package

on:
  release:
    types: [created]  # Dieser Workflow wird bei der Erstellung einer GitHub-Release ausgelöst

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'adoptopenjdk'  # Alternativ kannst du auch 'openjdk' verwenden
        server-id: github  # Entspricht dem ID-Wert in der distributionManagement/repository/id in deiner pom.xml
        settings-path: ${{ github.workspace }}  # Verwende den Arbeitsbereich für das settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Das Token, das vom GitHub Actions Runner bereitgestellt wird
